<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ActusInsurance.Core</AssemblyName>
    <RootNamespace>ActusInsurance.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Shared\" />
  </ItemGroup>
</Project>
